import { expect, it } from 'vitest';
import { JSDOM } from 'jsdom';
import { renderArticlePreview } from '../source/admin/article-preview.js';
const element=()=>new JSDOM('<main></main>').window.document.querySelector('main');
it('renders Markdown and theme components without changing source',async()=>{const el=element();await renderArticlePreview({element:el,markdown:'# 标题\n\n| A | B |\n|---|---|\n|1|2|\n\n```javascript\nconst a=1;\n```\n\n![说明](/media/a.webp)\n\n{% note info %}\n重点\n{% endnote %}\n\n{% folding 更多 %}\n隐藏内容\n{% endfolding %}\n\n{% link 文档, 官网, https://example.com,  %}\n\n{% tabs demo %}\n<!-- tab 第一项 -->\n内容\n<!-- endtab -->\n{% endtabs %}'});expect(el.querySelector('h1').textContent).toBe('标题');expect(el.querySelector('table')).not.toBeNull();expect(el.querySelector('code.language-javascript')).not.toBeNull();expect(el.querySelector('figcaption').textContent).toBe('说明');expect(el.querySelector('details summary').textContent).toBe('更多');expect(el.querySelector('[role=tab]')).not.toBeNull();expect(el.querySelector('.preview-link')).not.toBeNull();});
it('removes executable HTML and unsafe URLs',async()=>{const el=element();await renderArticlePreview({element:el,markdown:'<script>alert(1)</script>\n<img src=x onerror="alert(1)">\n[x](javascript:alert%281%29)'});expect(el.querySelector('script,[onerror],a[href^="javascript:"]')).toBeNull();});
it('shows a failed diagram safely with its source',async()=>{const el=element();await renderArticlePreview({element:el,markdown:'{% mermaid %}\nnot a diagram\n{% endmermaid %}'});expect(el.textContent).toContain('流程图无法渲染');expect(el.textContent).toContain('not a diagram');});
it('does not let an aborted render overwrite current content',async()=>{const el=element(),controller=new AbortController();controller.abort();await renderArticlePreview({element:el,markdown:'旧正文',signal:controller.signal});expect(el.textContent).toBe('');await renderArticlePreview({element:el,markdown:'新正文'});expect(el.textContent.trim()).toBe('新正文');});
it('ignores a diagram preview that finishes after newer Markdown',async()=>{const el=element();const old=renderArticlePreview({element:el,markdown:'{% mermaid %}\nnot a diagram\n{% endmermaid %}'});await renderArticlePreview({element:el,markdown:'最新正文'});await old;expect(el.textContent.trim()).toBe('最新正文');});
