import { afterEach, expect, it, vi } from 'vitest';
import { JSDOM } from 'jsdom';
import { readFileSync } from 'node:fs';
import { mountArticleEditor } from '../source/admin/article-editor-ui.js';
afterEach(()=>vi.unstubAllGlobals());
class Engine {constructor(el,options){this.options=options;this.value='';queueMicrotask(()=>options.after());}setValue(value){this.value=value;}getValue(){return this.value;}insertMD(value){this.value+=value;this.options.input(this.value);}disabled(){}enable(){}destroy(){}}
async function setup(){const dom=new JSDOM(readFileSync('source/admin/index.html','utf8'));vi.stubGlobal('document',dom.window.document);vi.stubGlobal('Event',dom.window.Event);vi.stubGlobal('Vditor',Engine);dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};const changed=[],errors=[],uploads=[];const editor=await mountArticleEditor({element:document.querySelector('#article-editor'),sourceInput:document.querySelector('#body'),onChange:md=>changed.push(md),onError:error=>errors.push(error.message),chooseImage:cb=>uploads.push(cb)});return {editor,changed,errors,uploads};}
it('exposes grouped insertion tools and keeps the persisted body synchronized',async()=>{const {editor,changed}=await setup();editor.load('原文');expect(changed).toEqual([]);document.querySelector('[data-editor-mode=source]').click();document.querySelector('textarea[aria-label]').value='最新正文';document.querySelector('textarea[aria-label]').dispatchEvent(new Event('input',{bubbles:true}));expect(document.querySelector('#body').value).toBe('最新正文');for(const type of ['link','note','folding','tabs','mermaid','code','image'])expect(document.querySelector(`[data-insert=${type}]`).textContent.trim()).not.toBe('');expect(document.querySelector('[name=description]')).not.toBeNull();});
it('inserts a theme card through fields and cancels without changing content',async()=>{const {editor}=await setup();editor.load('正文');document.querySelector('[data-insert=link]').click();document.querySelector('[name=component-title]').value='文档';document.querySelector('[name=component-url]').value='https://example.com';document.querySelector('[data-component-confirm]').click();expect(editor.getMarkdown()).toContain('{% link 文档, , https://example.com,  %}');const saved=editor.getMarkdown();document.querySelector('[data-insert=note]').click();document.querySelector('[data-component-cancel]').click();expect(editor.getMarkdown()).toBe(saved);});
it('keeps source content after invalid component input',async()=>{const {editor,errors}=await setup();editor.load('保留正文');document.querySelector('[data-insert=link]').click();document.querySelector('[name=component-title]').value='文档';document.querySelector('[name=component-url]').value='javascript:alert(1)';document.querySelector('[data-component-confirm]').click();expect(editor.getMarkdown()).toBe('保留正文');expect(document.querySelector('[data-component-error]').textContent).toMatch(/地址/);});
it('ignores delayed image insertion after another article is loaded',async()=>{const {editor,uploads}=await setup();editor.load('文章一');document.querySelector('#upload-body').click();editor.load('文章二');uploads[0]('/media/old.webp');expect(editor.getMarkdown()).toBe('文章二');});
it('inserts an uploaded image at the selected source location with escaped caption',async()=>{const {editor,uploads}=await setup();editor.load('前 后');editor.setMode('source');const area=document.querySelector('textarea[aria-label]');area.setSelectionRange(2,2);document.querySelector('#image-alt').value='说明[一]';document.querySelector('#upload-body').click();uploads[0]('/media/new.webp');expect(editor.getMarkdown()).toBe('前 \n![说明\\[一\\]](/media/new.webp)\n后');});
